GunName:
  AK-47: 1
  Type20-ar: 2
  Type20-smg: 3
  mp45: 4
  Type20-hg: 5
  Type20-lmg: 6
  Type20-sr: 7
  AR14: 8
  AR14-sc: 9
  AR14-ebr: 10
  AH33: 11
  AH33-bp: 12
  PP33: 13
  RPH: 14
  SVH: 15
  BR700: 16
  Type20-sc: 17
  M17: 18
  SR23: 19
  LMG25: 20
  APH38: 21
  KRPX22: 22
  Cal45: 23
  Cal45-ira: 24
  tanegashima: 25
  12g_7: 26
  sg078: 27
  sd10_22: 28
  rph_zombiepanic: 29
  tsubura_revolver: 30
  BR700-skelton: 31
  pp33_toxic: 32
  m9_combat: 33
  m9: 34
  flechette_rifle: 35
  dmag_10: 36
  biene22: 37
  aph38_aqua: 38
  AR14-sc-ender: 39
  pasta_12: 40